costmap:
    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    global_frame: map
    robot_base_frame: base_footprint
    static_map: false
    rolling_window: true
    resolution: 1
    update_frequency: 20
    publish_frequency: 20
    width: 10
    height: 10
    obstacle_range: 10.0
    raytrace_range: 10.0
    transform_tolerance: 1.0
    robot_radius: 0.50
    always_send_full_costmap: true
    unknown_cost_value: 10
    track_unknown_space: true
    origin_x: 0.0
    origin_y: 0.0


    inflation_layer:
      enabled: true
      inflation_radius: 0.1
    
    obstacle_layer:
      enabled: true
      origin_z: 0.0
      z_voxels: 2
      max_obstacle_height: 1.4
      observation_sources: scan bump
      scan:
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        min_obstacle_height: 0.0
        max_obstacle_height: 0.35
      bump:
        data_type: PointCloud2
        topic: mobile_base/sensors/bumper_pointcloud
        marking: true
        clearing: true
        min_obstacle_height: 0.0
        max_obstacle_height: 0.15
